exclude:
- README.md
- LICENSE
- vendor
- reveal.js

plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-default-layout
- jekyll-include-cache

encoding: utf-8
title: OpenUTD
lang: en-US

logo: "/assets/tux_logo.png"
favicon: "/assets/favicon.png"

navigation_header:
  Home: /
  About: /about.html
  Contact: /contact.html
  Events: /events/
  Categories: /categories.html

navigation_footer:
  OpenUTD: /

paginate: 3
paginate_path: "/events/page:num"
future: true
collections:
  posts:
    title: Events
    output: true
